#######################
# Theme Customization #
#######################

title: '@garambo'                           # used in <title> tag & site header
author: Vincenzo Garambone                  # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Vincenzo Garambone's personal page & blog.
  Thoughts about programming, music & video games.
slogan: \> Hello.                           # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/background.svg                   # used as background in site header
url:                                        # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/garamb1/garamb1.github.io # used in footer
highlighter: rouge

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Home
    url: /
    icon: /i/icons/posts.svg # icons should be 24x24 px.
    icon-white: /i/icons/posts_white.svg
  - name: Projects
    url: /projects
    icon: /i/icons/portfolio.svg
    icon-white: /i/icons/portfolio_white.svg
  - name: About
    url: /about
    icon: /i/icons/about.svg
    icon-white: /i/icons/about_white.svg

# Objects listed here will appear on the /projects.html page.
projects:
  - title: RetroSearch
    teaser: |
      Search and Browse the WWW like it's 1997. 
      RetroSearch is a Spring Web Application that presents very simple HTML pages which can be interpreted by old browsers.
      It provides the ability to search the Web using DuckDuckGo with a custom scraper that loads the first page of results and allows you to browse pages in plain text
    url: https://github.com/garamb1/retrosearch
    role: Developer
    category: Web Development
  - title: Casalbruciato Runner
    teaser: An infinite runner set in Rome's neighborhood of CasalBruciato. Available on Google Play.
    url: https://play.google.com/store/apps/details?id=it.garambo.Casalbruciato
    role: Developer
    category: Game Development
  - title: StartSaver
    teaser: With StartSaver you can lock the screen or start your screensaver when you are getting away from your Mac.
    url: https://github.com/garamb1/StartSaver/releases
    role: Developer
    category: macOS App

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  style: compressed
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
